import type { ProviderDef } from "./types";

/**
 * Catálogo de proveedores. La `family` define el adaptador para chat/embeddings;
 * para imagen/otros el registry rutea por `id`. Agregar uno = una fila acá.
 */
export const PROVIDERS: ProviderDef[] = [
  // ── Chat: familia openai-compatible (mismo protocolo, distinto baseURL) ──────
  {
    id: "openai",
    name: "OpenAI",
    family: "openai-compatible",
    kind: "direct",
    auth: "api_key",
    capabilities: ["chat", "embedding", "image", "tts", "stt"],
    baseURL: "https://api.openai.com/v1",
    docsUrl: "https://platform.openai.com/api-keys",
    keyHint: "platform.openai.com",
  },
  {
    id: "azure_openai",
    name: "Azure OpenAI",
    family: "openai-compatible",
    kind: "direct",
    auth: "api_key+endpoint",
    capabilities: ["chat", "embedding"],
    keyHint: "Azure Portal",
  },
  {
    id: "xai",
    name: "xAI (Grok)",
    family: "openai-compatible",
    kind: "direct",
    auth: "api_key",
    capabilities: ["chat"],
    baseURL: "https://api.x.ai/v1",
    keyHint: "console.x.ai",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    family: "openai-compatible",
    kind: "direct",
    auth: "api_key",
    capabilities: ["chat"],
    baseURL: "https://api.deepseek.com/v1",
  },
  {
    id: "mistral",
    name: "Mistral",
    family: "openai-compatible",
    kind: "direct",
    auth: "api_key",
    capabilities: ["chat", "embedding", "ocr"],
    baseURL: "https://api.mistral.ai/v1",
  },
  {
    id: "groq",
    name: "Groq",
    family: "openai-compatible",
    kind: "direct",
    auth: "api_key",
    capabilities: ["chat", "stt"],
    baseURL: "https://api.groq.com/openai/v1",
  },
  {
    id: "together",
    name: "Together AI",
    family: "openai-compatible",
    kind: "aggregator",
    auth: "api_key",
    capabilities: ["chat", "embedding", "image"],
    baseURL: "https://api.together.xyz/v1",
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    family: "openai-compatible",
    kind: "aggregator",
    auth: "api_key",
    capabilities: ["chat", "embedding", "image"],
    baseURL: "https://api.fireworks.ai/inference/v1",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    family: "openai-compatible",
    kind: "direct",
    auth: "api_key",
    capabilities: ["chat"],
    baseURL: "https://api.perplexity.ai",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    family: "openai-compatible",
    kind: "aggregator",
    auth: "api_key",
    capabilities: ["chat"],
    baseURL: "https://openrouter.ai/api/v1",
    keyHint: "openrouter.ai/keys",
  },
  {
    id: "deepinfra",
    name: "DeepInfra",
    family: "openai-compatible",
    kind: "aggregator",
    auth: "api_key",
    capabilities: ["chat", "embedding"],
    baseURL: "https://api.deepinfra.com/v1/openai",
  },
  {
    id: "novita",
    name: "Novita",
    family: "openai-compatible",
    kind: "aggregator",
    auth: "api_key",
    capabilities: ["chat"],
    baseURL: "https://api.novita.ai/v3/openai",
  },
  {
    id: "sambanova",
    name: "SambaNova",
    family: "openai-compatible",
    kind: "direct",
    auth: "api_key",
    capabilities: ["chat"],
    baseURL: "https://api.sambanova.ai/v1",
  },
  {
    id: "cerebras",
    name: "Cerebras",
    family: "openai-compatible",
    kind: "direct",
    auth: "api_key",
    capabilities: ["chat"],
    baseURL: "https://api.cerebras.ai/v1",
  },
  {
    id: "qwen",
    name: "Alibaba Qwen",
    family: "openai-compatible",
    kind: "direct",
    auth: "api_key",
    capabilities: ["chat", "embedding"],
    baseURL: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
  },
  {
    id: "moonshot",
    name: "Moonshot (Kimi)",
    family: "openai-compatible",
    kind: "direct",
    auth: "api_key",
    capabilities: ["chat"],
    baseURL: "https://api.moonshot.ai/v1",
  },
  {
    id: "zhipu",
    name: "Zhipu GLM",
    family: "openai-compatible",
    kind: "direct",
    auth: "api_key",
    capabilities: ["chat"],
    baseURL: "https://open.bigmodel.cn/api/paas/v4",
  },
  {
    id: "meta",
    name: "Meta Llama API",
    family: "openai-compatible",
    kind: "direct",
    auth: "api_key",
    capabilities: ["chat"],
    baseURL: "https://api.llama.com/compat/v1",
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM",
    family: "openai-compatible",
    kind: "aggregator",
    auth: "api_key",
    capabilities: ["chat", "embedding"],
    baseURL: "https://integrate.api.nvidia.com/v1",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    family: "openai-compatible",
    kind: "aggregator",
    auth: "api_key",
    capabilities: ["chat"],
    baseURL: "https://router.huggingface.co/v1",
  },
  {
    id: "ollama",
    name: "Ollama (local)",
    family: "openai-compatible",
    kind: "local",
    auth: "api_key",
    capabilities: ["chat", "embedding"],
    baseURL: "http://localhost:11434/v1",
    keyHint: "local, sin key",
  },
  {
    id: "lmstudio",
    name: "LM Studio (local)",
    family: "openai-compatible",
    kind: "local",
    auth: "api_key",
    capabilities: ["chat", "embedding"],
    baseURL: "http://localhost:1234/v1",
    keyHint: "local, sin key",
  },
  {
    id: "ai21",
    name: "AI21 (Jamba)",
    family: "openai-compatible",
    kind: "direct",
    auth: "api_key",
    capabilities: ["chat"],
    baseURL: "https://api.ai21.com/studio/v1",
  },
  {
    id: "writer",
    name: "Writer (Palmyra)",
    family: "openai-compatible",
    kind: "direct",
    auth: "api_key",
    capabilities: ["chat"],
    baseURL: "https://api.writer.com/v1",
  },
  {
    id: "cohere",
    name: "Cohere",
    family: "openai-compatible",
    kind: "direct",
    auth: "api_key",
    capabilities: ["chat", "embedding", "rerank"],
    baseURL: "https://api.cohere.ai/compatibility/v1",
  },

  // ── Chat: familias propias ───────────────────────────────────────────────────
  {
    id: "anthropic",
    name: "Anthropic",
    family: "anthropic",
    kind: "direct",
    auth: "api_key",
    capabilities: ["chat"],
    docsUrl: "https://console.anthropic.com/settings/keys",
    keyHint: "console.anthropic.com",
  },
  {
    id: "bedrock",
    name: "Amazon Bedrock",
    family: "bedrock",
    kind: "aggregator",
    auth: "aws",
    capabilities: ["chat", "embedding", "image"],
    keyHint: "AWS keys + región",
  },
  {
    id: "google",
    name: "Google (Gemini)",
    family: "gemini",
    kind: "direct",
    auth: "api_key",
    capabilities: ["chat", "embedding", "image"],
    docsUrl: "https://aistudio.google.com/apikey",
    keyHint: "aistudio.google.com",
  },

  // ── Imagen: directos ─────────────────────────────────────────────────────────
  {
    id: "stability",
    name: "Stability AI",
    family: "stability",
    kind: "direct",
    auth: "api_key",
    capabilities: ["image", "music"],
    baseURL: "https://api.stability.ai",
  },
  {
    id: "bfl",
    name: "Black Forest Labs (FLUX)",
    family: "bfl",
    kind: "direct",
    auth: "api_key",
    capabilities: ["image"],
    baseURL: "https://api.bfl.ai",
  },
  {
    id: "ideogram",
    name: "Ideogram",
    family: "ideogram",
    kind: "direct",
    auth: "api_key",
    capabilities: ["image"],
    baseURL: "https://api.ideogram.ai",
  },
  {
    id: "recraft",
    name: "Recraft",
    family: "recraft",
    kind: "direct",
    auth: "api_key",
    capabilities: ["image"],
    baseURL: "https://external.api.recraft.ai",
  },
  {
    id: "leonardo",
    name: "Leonardo AI",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["image"],
  },
  {
    id: "adobe_firefly",
    name: "Adobe Firefly",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["image", "video"],
  },
  {
    id: "bytedance",
    name: "ByteDance (Seedream/Seedance)",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["image", "video"],
  },
  {
    id: "reve",
    name: "Reve",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["image"],
  },
  {
    id: "bria",
    name: "Bria",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["image"],
  },
  {
    id: "playground",
    name: "Playground",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["image"],
  },

  // ── Agregadores (imagen/video/audio/música, cientos de modelos) ──────────────
  {
    id: "replicate",
    name: "Replicate",
    family: "replicate",
    kind: "aggregator",
    auth: "api_key",
    capabilities: ["image", "video", "music", "tts", "stt"],
    baseURL: "https://api.replicate.com/v1",
    keyHint: "replicate.com/account/api-tokens",
  },
  {
    id: "fal",
    name: "fal.ai",
    family: "fal",
    kind: "aggregator",
    auth: "api_key",
    capabilities: ["image", "video", "music", "tts"],
    baseURL: "https://fal.run",
    keyHint: "fal.ai/dashboard/keys",
  },
  {
    id: "luma",
    name: "Luma (Photon/Dream Machine)",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["image", "video"],
  },
  {
    id: "krea",
    name: "Krea",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["image", "video"],
  },

  // ── Video (catálogo ahora) ───────────────────────────────────────────────────
  {
    id: "google_veo",
    name: "Google Veo",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["video"],
  },
  {
    id: "openai_sora",
    name: "OpenAI Sora",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["video"],
  },
  {
    id: "runway",
    name: "Runway",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["video"],
  },
  {
    id: "kling",
    name: "Kling",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["video"],
  },
  {
    id: "pika",
    name: "Pika",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["video"],
  },
  {
    id: "minimax",
    name: "MiniMax (Hailuo)",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["video", "tts", "music"],
  },
  {
    id: "higgsfield",
    name: "Higgsfield",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["video"],
  },
  {
    id: "alibaba_wan",
    name: "Alibaba Wan",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["video"],
  },
  {
    id: "vidu",
    name: "Vidu",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["video"],
  },
  {
    id: "lightricks",
    name: "Lightricks (LTX)",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["video"],
  },
  {
    id: "tencent_hunyuan",
    name: "Tencent Hunyuan",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["video", "image"],
  },
  {
    id: "genmo",
    name: "Genmo (Mochi)",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["video"],
  },
  {
    id: "haiper",
    name: "Haiper",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["video"],
  },

  // ── Avatar / talking-head (catálogo ahora) ───────────────────────────────────
  {
    id: "heygen",
    name: "HeyGen",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["avatar"],
  },
  {
    id: "synthesia",
    name: "Synthesia",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["avatar"],
  },
  {
    id: "did",
    name: "D-ID",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["avatar"],
  },
  {
    id: "tavus",
    name: "Tavus",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["avatar"],
  },
  {
    id: "sync",
    name: "Sync.so (lip-sync)",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["avatar"],
  },

  // ── Embeddings (directos extra a openai-compatible) ──────────────────────────
  {
    id: "voyage",
    name: "Voyage AI",
    family: "openai-compatible",
    kind: "direct",
    auth: "api_key",
    capabilities: ["embedding", "rerank"],
    baseURL: "https://api.voyageai.com/v1",
  },
  {
    id: "jina",
    name: "Jina AI",
    family: "openai-compatible",
    kind: "direct",
    auth: "api_key",
    capabilities: ["embedding", "rerank"],
    baseURL: "https://api.jina.ai/v1",
  },
  {
    id: "nomic",
    name: "Nomic",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["embedding"],
  },
  {
    id: "cloudflare",
    name: "Cloudflare Workers AI",
    family: "bespoke",
    kind: "direct",
    auth: "api_key+endpoint",
    capabilities: ["embedding", "chat", "image"],
  },

  // ── Audio: TTS (catálogo ahora) ──────────────────────────────────────────────
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    family: "elevenlabs",
    kind: "direct",
    auth: "api_key",
    capabilities: ["tts", "stt", "music"],
    baseURL: "https://api.elevenlabs.io",
  },
  {
    id: "cartesia",
    name: "Cartesia",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["tts"],
  },
  {
    id: "playht",
    name: "PlayHT",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["tts"],
  },
  {
    id: "hume",
    name: "Hume",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["tts"],
  },
  {
    id: "polly",
    name: "Amazon Polly",
    family: "bespoke",
    kind: "direct",
    auth: "aws",
    capabilities: ["tts"],
  },
  {
    id: "azure_speech",
    name: "Azure Speech",
    family: "bespoke",
    kind: "direct",
    auth: "api_key+endpoint",
    capabilities: ["tts", "stt"],
  },
  {
    id: "fish",
    name: "Fish Audio",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["tts"],
  },
  {
    id: "rime",
    name: "Rime",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["tts"],
  },
  {
    id: "lmnt",
    name: "LMNT",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["tts"],
  },
  {
    id: "resemble",
    name: "Resemble AI",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["tts"],
  },
  {
    id: "cambai",
    name: "Camb.ai",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["tts"],
  },

  // ── Audio: STT (catálogo ahora) ──────────────────────────────────────────────
  {
    id: "deepgram",
    name: "Deepgram",
    family: "deepgram",
    kind: "direct",
    auth: "api_key",
    capabilities: ["stt"],
  },
  {
    id: "assemblyai",
    name: "AssemblyAI",
    family: "assemblyai",
    kind: "direct",
    auth: "api_key",
    capabilities: ["stt"],
  },
  {
    id: "speechmatics",
    name: "Speechmatics",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["stt"],
  },
  {
    id: "gladia",
    name: "Gladia",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["stt"],
  },

  // ── Música (catálogo ahora) ──────────────────────────────────────────────────
  {
    id: "suno",
    name: "Suno",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["music"],
  },
  {
    id: "udio",
    name: "Udio",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["music"],
  },
  {
    id: "google_lyria",
    name: "Google Lyria",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["music"],
  },

  // ── OCR / documentos (catálogo ahora) ────────────────────────────────────────
  {
    id: "llamaparse",
    name: "LlamaParse",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["ocr"],
  },
  {
    id: "google_docai",
    name: "Google Document AI",
    family: "bespoke",
    kind: "direct",
    auth: "api_key+endpoint",
    capabilities: ["ocr"],
  },
  {
    id: "aws_textract",
    name: "AWS Textract",
    family: "bespoke",
    kind: "direct",
    auth: "aws",
    capabilities: ["ocr"],
  },
  {
    id: "azure_docai",
    name: "Azure Document Intelligence",
    family: "bespoke",
    kind: "direct",
    auth: "api_key+endpoint",
    capabilities: ["ocr"],
  },
  {
    id: "reducto",
    name: "Reducto",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["ocr"],
  },
  {
    id: "unstructured",
    name: "Unstructured",
    family: "bespoke",
    kind: "direct",
    auth: "api_key",
    capabilities: ["ocr"],
  },
];

// KNOW-5: mark each provider as implemented based on whether its family has a
// working adapter. `bespoke` has no adapter → false for all bespoke providers.
const IMPLEMENTED_FAMILIES = new Set<import("./types").Family>([
  "openai-compatible",
  "anthropic",
  "gemini",
  "openai-images",
  "google-imagen",
  "stability",
  "bfl",
  "ideogram",
  "recraft",
  "replicate",
  "fal",
  "elevenlabs",
  "deepgram",
  "assemblyai",
]);
for (const p of PROVIDERS) {
  p.implemented = IMPLEMENTED_FAMILIES.has(p.family);
}

export const PROVIDERS_BY_ID: Record<string, ProviderDef> = Object.fromEntries(
  PROVIDERS.map((p) => [p.id, p])
);

export function getProvider(id: string): ProviderDef | undefined {
  return PROVIDERS_BY_ID[id];
}
