import { isSenderAllowed } from "@/lib/channels/allowlist";
import { checkCommandPlace } from "@/lib/channels/place";
import { NextResponse, after } from "next/server";
import { schema } from "@orchester/db";
import { eq } from "drizzle-orm";
import { handleInbound } from "@/lib/channels/router";
import { withCrossTenantAdmin } from "@/lib/tenant/cron";
import { safeLogError } from "@/lib/safe-log";
import {
  DISCORD_APPLICATION_COMMAND,
  DISCORD_DEFERRED_REPLY,
  DISCORD_EPHEMERAL,
  DISCORD_OPTION_NAME,
  DISCORD_PING,
  DISCORD_PONG,
  DISCORD_REPLY,
  decodeDiscordCredentials,
  discordCommandName,
  discordEditReply,
  discordRepliesArePublic,
  discordThreadContext,
  interactionSender,
  interactionText,
  verifyDiscordSignature,
  type DiscordInteraction,
} from "@/lib/channels/discord";

/**
 * Public Discord interactions endpoint. Configure in the Discord application:
 *   General Information → Interactions Endpoint URL
 *     = https://your-domain.com/api/channels/discord/webhook/{secret}
 *
 * The `{secret}` is generated by Orchester when the channel is created and
 * lives in `channel.secret`. Discord additionally signs every request with
 * Ed25519 — saving the URL only succeeds if a corrupted signature gets a 401.
 *
 * Discord drops the interaction if nothing answers within three seconds, and
 * an agent run takes longer than that. So the command is acknowledged with a
 * deferred reply and the answer is edited in afterwards, within Discord's
 * 15-minute window for the interaction token.
 */
function ephemeral(content: string) {
  return NextResponse.json({
    type: DISCORD_REPLY,
    data: { content, flags: DISCORD_EPHEMERAL },
  });
}

export async function POST(req: Request, { params }: { params: Promise<{ secret: string }> }) {
  const { secret } = await params;
  // Channel lookup by webhook secret. The Discord URL embeds the secret as the
  // only routing key — the workspace isn't known until the row resolves, so
  // this uses the cross-tenant bypass (audit-logged).
  const channel = await withCrossTenantAdmin("discord.webhook.channel_lookup", async (tx) => {
    const rows = await tx
      .select()
      .from(schema.channels)
      .where(eq(schema.channels.secret, secret))
      .limit(1);
    return rows[0];
  });
  if (!channel || channel.type !== "discord" || channel.status !== "active") {
    return NextResponse.json({ ok: false, error: "channel not found" }, { status: 404 });
  }

  const creds = decodeDiscordCredentials(channel.credentialsEncrypted);
  if (!creds) {
    return NextResponse.json({ ok: false, error: "channel missing credentials" }, { status: 500 });
  }

  // Discord signs the bytes as received, so the body must not be re-serialized.
  const rawBody = await req.text();
  if (
    !verifyDiscordSignature({
      publicKey: creds.publicKey,
      signatureHeader: req.headers.get("x-signature-ed25519"),
      timestampHeader: req.headers.get("x-signature-timestamp"),
      rawBody,
    })
  ) {
    return NextResponse.json({ ok: false, error: "invalid signature" }, { status: 401 });
  }

  let interaction: DiscordInteraction;
  try {
    interaction = JSON.parse(rawBody) as DiscordInteraction;
  } catch {
    return NextResponse.json({ ok: false, error: "invalid json" }, { status: 400 });
  }

  if (interaction.type === DISCORD_PING) {
    return NextResponse.json({ type: DISCORD_PONG });
  }
  if (interaction.type !== DISCORD_APPLICATION_COMMAND) {
    return NextResponse.json({ ok: true });
  }

  const expected = discordCommandName(channel.config);
  if (interaction.data?.name !== expected) {
    return ephemeral(`Unknown command. This channel answers to /${expected}.`);
  }

  const sender = interactionSender(interaction);
  if (!sender) {
    return ephemeral("Discord did not identify who ran this command.");
  }

  if (!isSenderAllowed(channel.config, sender)) {
    // The refusal needs no agent, so it answers straight away — and only the
    // person who ran the command sees their own ID.
    return ephemeral(`You do not have access. Your ID: ${sender.id}.`);
  }

  // Who may ask is not the same question as where they may ask it. An
  // allowlisted person running this in a public channel with
  // `config.publicReplies` on would have the agent's answer posted for that
  // whole server to read. Until now `guild_id` and `channel_id` were only
  // written to the conversation metadata, never checked.
  const place = checkCommandPlace(channel.config, {
    guildId: interaction.guild_id,
    channelId: interaction.channel_id,
    // A thread is a channel with its own id. Discord's docs do not say whether
    // an interaction inside one reports the thread or its parent as
    // `channel_id`, but they do say the partial `channel` object carries
    // `parent_id` — so both are passed and the gate accepts either. Without
    // this, allowlisting a channel would refuse every thread opened inside it.
    parentId: interaction.channel?.parent_id,
  });
  if (place !== "ok") {
    // The id goes back so whoever configures the channel can add it without
    // digging through Discord's developer mode, and it is ephemeral so the
    // rest of the server does not see the refusal.
    return ephemeral(
      place === "guild-not-allowed"
        ? `This channel does not answer in this server. Server ID: ${interaction.guild_id ?? "none (direct message)"}.`
        : `This channel does not answer in this Discord channel. Channel ID: ${interaction.channel_id ?? "unknown"}.`
    );
  }

  const text = interactionText(interaction, DISCORD_OPTION_NAME);
  if (!text) {
    return ephemeral("Say something after the command and I will answer it.");
  }

  const token = interaction.token;
  if (!token) {
    return ephemeral("Discord sent no interaction token, so there is nothing to reply to.");
  }

  // Everything below runs after the deferred reply is already on its way.
  const conversationKey = `${interaction.channel_id ?? "dm"}:${sender.id}`;
  after(async () => {
    const say = async (content: string) => {
      try {
        await discordEditReply(creds.applicationId, token, content);
      } catch (e) {
        // Nothing else reports this: the HTTP response went out long ago, and
        // a swallowed failure here is a person left on "thinking…" forever.
        safeLogError("Discord edit reply failed:", e);
      }
    };
    // What this thread is about, read from the message it was opened on.
    // `parent_id` is present only inside a thread, and it is also what tells us
    // the channel to fetch that message from — a thread carries the id of its
    // starter message, but the message itself lives in the parent.
    //
    // Fetched every turn rather than seeded once: `externalId` is
    // `<thread>:<sender>`, so a conversation seeded for one person leaves the
    // next person in the same thread starting blank. Re-reading also keeps the
    // answer current if the card is edited.
    //
    // It never blocks a reply: on failure it comes back undefined and the turn
    // proceeds exactly as it did before.
    const parentId = interaction.channel?.parent_id;
    const threadContext =
      parentId && interaction.channel_id
        ? await discordThreadContext({
            botToken: creds.botToken,
            parentId,
            threadId: interaction.channel_id,
          })
        : undefined;

    try {
      const result = await handleInbound(channel.workspaceId, {
        channelId: channel.id,
        // One conversation per person per Discord channel.
        externalId: conversationKey,
        text,
        ...(threadContext ? { context: threadContext } : {}),
        ...(sender.username ? { customerName: sender.username } : {}),
        metadata: {
          source: "discord",
          discordUserId: sender.id,
          discordChannelId: interaction.channel_id,
          discordGuildId: interaction.guild_id,
        },
      });
      await say(result.reply || "I have no answer for that.");
    } catch (e) {
      // The message lands in a chat room, so it says nothing about what broke:
      // the thrown error can carry a SQL statement, a provider's response body
      // or an internal hostname. The detail goes to the log instead.
      safeLogError("Discord inbound failed:", e);
      await say("Something went wrong on my side. It has been logged.");
    }
  });

  return NextResponse.json({
    type: DISCORD_DEFERRED_REPLY,
    // Visibility is fixed here and cannot be changed by the later edit, so a
    // channel that has not asked for public answers gets private ones.
    ...(discordRepliesArePublic(channel.config) ? {} : { data: { flags: DISCORD_EPHEMERAL } }),
  });
}
