import { isSenderAllowed } from "@/lib/channels/allowlist";
import { NextResponse, after } from "next/server";
import { schema } from "@orchester/db";
import { eq } from "drizzle-orm";
import { handleInbound } from "@/lib/channels/router";
import { withCrossTenantAdmin } from "@/lib/tenant/cron";
import {
  DISCORD_APPLICATION_COMMAND,
  DISCORD_DEFERRED_REPLY,
  DISCORD_EPHEMERAL,
  DISCORD_OPTION_NAME,
  DISCORD_PING,
  DISCORD_PONG,
  DISCORD_REPLY,
  decodeDiscordCredentials,
  discordCommandName,
  discordEditReply,
  interactionSender,
  interactionText,
  verifyDiscordSignature,
  type DiscordInteraction,
} from "@/lib/channels/discord";

/**
 * Public Discord interactions endpoint. Configure in the Discord application:
 *   General Information → Interactions Endpoint URL
 *     = https://your-domain.com/api/channels/discord/webhook/{secret}
 *
 * The `{secret}` is generated by Orchester when the channel is created and
 * lives in `channel.secret`. Discord additionally signs every request with
 * Ed25519 — saving the URL only succeeds if a corrupted signature gets a 401.
 *
 * Discord drops the interaction if nothing answers within three seconds, and
 * an agent run takes longer than that. So the command is acknowledged with a
 * deferred reply and the answer is edited in afterwards, within Discord's
 * 15-minute window for the interaction token.
 */
function ephemeral(content: string) {
  return NextResponse.json({
    type: DISCORD_REPLY,
    data: { content, flags: DISCORD_EPHEMERAL },
  });
}

export async function POST(req: Request, { params }: { params: Promise<{ secret: string }> }) {
  const { secret } = await params;
  // Channel lookup by webhook secret. The Discord URL embeds the secret as the
  // only routing key — the workspace isn't known until the row resolves, so
  // this uses the cross-tenant bypass (audit-logged).
  const channel = await withCrossTenantAdmin("discord.webhook.channel_lookup", async (tx) => {
    const rows = await tx
      .select()
      .from(schema.channels)
      .where(eq(schema.channels.secret, secret))
      .limit(1);
    return rows[0];
  });
  if (!channel || channel.type !== "discord" || channel.status !== "active") {
    return NextResponse.json({ ok: false, error: "channel not found" }, { status: 404 });
  }

  const creds = decodeDiscordCredentials(channel.credentialsEncrypted);
  if (!creds) {
    return NextResponse.json({ ok: false, error: "channel missing credentials" }, { status: 500 });
  }

  // Discord signs the bytes as received, so the body must not be re-serialized.
  const rawBody = await req.text();
  if (
    !verifyDiscordSignature({
      publicKey: creds.publicKey,
      signatureHeader: req.headers.get("x-signature-ed25519"),
      timestampHeader: req.headers.get("x-signature-timestamp"),
      rawBody,
    })
  ) {
    return NextResponse.json({ ok: false, error: "invalid signature" }, { status: 401 });
  }

  let interaction: DiscordInteraction;
  try {
    interaction = JSON.parse(rawBody) as DiscordInteraction;
  } catch {
    return NextResponse.json({ ok: false, error: "invalid json" }, { status: 400 });
  }

  if (interaction.type === DISCORD_PING) {
    return NextResponse.json({ type: DISCORD_PONG });
  }
  if (interaction.type !== DISCORD_APPLICATION_COMMAND) {
    return NextResponse.json({ ok: true });
  }

  const expected = discordCommandName(channel.config);
  if (interaction.data?.name !== expected) {
    return ephemeral(`Unknown command. This channel answers to /${expected}.`);
  }

  const sender = interactionSender(interaction);
  if (!sender) {
    return ephemeral("Discord did not identify who ran this command.");
  }

  const allowed = channel.config?.["allowedSenders"] as string[] | undefined;
  if (!isSenderAllowed(allowed, sender)) {
    // The refusal needs no agent, so it answers straight away — and only the
    // person who ran the command sees their own ID.
    return ephemeral(`You do not have access. Your ID: ${sender.id}.`);
  }

  const text = interactionText(interaction, DISCORD_OPTION_NAME);
  if (!text) {
    return ephemeral("Say something after the command and I will answer it.");
  }

  const token = interaction.token;
  if (!token) {
    return ephemeral("Discord sent no interaction token, so there is nothing to reply to.");
  }

  // Everything below runs after the deferred reply is already on its way.
  const conversationKey = `${interaction.channel_id ?? "dm"}:${sender.id}`;
  after(async () => {
    try {
      const result = await handleInbound(channel.workspaceId, {
        channelId: channel.id,
        // One conversation per person per Discord channel.
        externalId: conversationKey,
        text,
        ...(sender.username ? { customerName: sender.username } : {}),
        metadata: {
          source: "discord",
          discordUserId: sender.id,
          discordChannelId: interaction.channel_id,
          discordGuildId: interaction.guild_id,
        },
      });
      await discordEditReply(
        creds.applicationId,
        token,
        result.reply || "I have no answer for that."
      );
    } catch (e) {
      // Without this the person is left looking at "thinking…" forever.
      await discordEditReply(
        creds.applicationId,
        token,
        `Something went wrong: ${e instanceof Error ? e.message : String(e)}`
      ).catch(() => undefined);
    }
  });

  return NextResponse.json({ type: DISCORD_DEFERRED_REPLY });
}
