-- packages/db/migrations/0009_rls_force_critical.down.sql

ALTER TABLE security_event NO FORCE ROW LEVEL SECURITY;
ALTER TABLE api_key NO FORCE ROW LEVEL SECURITY;
ALTER TABLE workspace_integration NO FORCE ROW LEVEL SECURITY;
ALTER TABLE ai_provider NO FORCE ROW LEVEL SECURITY;
ALTER TABLE gdpr_export_job NO FORCE ROW LEVEL SECURITY;
ALTER TABLE feature_flag NO FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_log NO FORCE ROW LEVEL SECURITY;
ALTER TABLE conversation NO FORCE ROW LEVEL SECURITY;
ALTER TABLE knowledge_chunk NO FORCE ROW LEVEL SECURITY;
ALTER TABLE agent_memory NO FORCE ROW LEVEL SECURITY;
