-- packages/db/migrations/0010_rls_force_rest.down.sql

ALTER TABLE idempotency_key NO FORCE ROW LEVEL SECURITY;
ALTER TABLE outbound_webhook NO FORCE ROW LEVEL SECURITY;
ALTER TABLE notification_pref NO FORCE ROW LEVEL SECURITY;
ALTER TABLE conversation_label NO FORCE ROW LEVEL SECURITY;
ALTER TABLE knowledge_doc NO FORCE ROW LEVEL SECURITY;
ALTER TABLE knowledge_base NO FORCE ROW LEVEL SECURITY;
ALTER TABLE flow_run NO FORCE ROW LEVEL SECURITY;
ALTER TABLE flow NO FORCE ROW LEVEL SECURITY;
ALTER TABLE employee NO FORCE ROW LEVEL SECURITY;
ALTER TABLE channel NO FORCE ROW LEVEL SECURITY;
ALTER TABLE agent NO FORCE ROW LEVEL SECURITY;
ALTER TABLE team NO FORCE ROW LEVEL SECURITY;
