-- packages/db/migrations/0053_drop_legacy_brain_residue.down.sql
--
-- Down migration for 0053. Intentionally a no-op: the dropped tables
-- are legacy host-side memory state whose data already lives upstream
-- in the @mnemosyne/server DB. Restoring empty CREATE TABLE statements
-- here would resurrect dead schemas without their data and confuse the
-- model authority — Mnemosyne owns memory now.
--
-- If a true revert is needed (incident recovery), restore from a
-- pre-Phase-3 backup of the orchester DB rather than running this.
SELECT 1;
