#!/usr/bin/env bash
#
# Instala el pre-commit hook que escanea secretos con gitleaks antes de
# permitir el commit.
#
# Uso (una vez por clon del repo):
#   ./scripts/install-git-hooks.sh
#
# Requiere `gitleaks` instalado:
#   brew install gitleaks         # macOS
#   apt install gitleaks          # Ubuntu (ver https://github.com/gitleaks/gitleaks)

set -euo pipefail
cd "$(dirname "$0")/.."

HOOK_FILE=".git/hooks/pre-commit"

cat > "$HOOK_FILE" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/install-git-hooks.sh — no edites a mano.
# Edita el script y reinstalá si necesitás cambios.

if ! command -v gitleaks >/dev/null 2>&1; then
  echo "[pre-commit] WARNING: gitleaks no instalado. Salteando secret scan."
  echo "[pre-commit] Instalá con: brew install gitleaks (o equivalente)."
  exit 0
fi

if ! gitleaks protect --staged --redact --config=.gitleaks.toml --no-banner; then
  echo ""
  echo "[pre-commit] ✗ Detectados secretos en los archivos staged."
  echo "[pre-commit] Si es un falso positivo, agregalo al [allowlist] de .gitleaks.toml"
  echo "[pre-commit] Si es real, removelo con: git restore --staged <archivo>"
  exit 1
fi
EOF

chmod +x "$HOOK_FILE"

echo "✓ pre-commit hook instalado en $HOOK_FILE"
echo ""
if ! command -v gitleaks >/dev/null 2>&1; then
  echo "⚠ Instalá gitleaks para que el hook sea funcional:"
  echo "   brew install gitleaks   # macOS"
fi
